### ISSUE TITLE
pip3

### ISSUE THREAD

**Issue by oceantiee** [grvmind/clubhouse_inviter#2]
![Снимок экрана (15)](https://user-images.githubusercontent.com/75776015/108716453-32ba9980-752d-11eb-8e4f-ed0b5a3ac400.png)

Косяк на стадии "$ pip3 install -r requirements.txt" 
Что делаю не так?

**Comment by grvmind** [comment]
pip3 не установлен. под винду наверное anaconda лучше юзать, ну или как то его установить. кстати python3 не запускается?
